package com.societyfy.notification.utils;

public interface NotificationExceptionConstants {
    String INTERNAL_SEVER_ERROR = "INTERNAL_SERVER_ERROR";
    String USER_NOT_FOUND = "USER_NOT_FOUND";

    String NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND";
    String NOTIFICATION_TYPE_NOT_FOUNT = "NOTIFICATION_TYPE_NOT_FOUNT";
    String NOTIFICATION_DELIVERY_TYPE_NOT_FOUNT = "NOTIFICATION_DELIVERY_TYPE_NOT_FOUNT";
}